### ISSUE TITLE
Planes flying below 500ft over the residential area

### ISSUE THREAD

**Issue by jzabel** [jzabel/aircraftnoiselogger#14]

**Comment by jzabel** [comment]
@hoopyfrood1006  - here is the query you need to validate planes flying below 500ft in our neighborhood. I used a geobox around my area of south superior, but feel free to extend:

SELECT time_position, callsign, latitude, longitude, geo_altitude, velocity, vertical_rate
FROM `superior-noise-loggers.aircraft_reporting_dataset.opensky-state-vector-reports` 
WHERE SAFE_CAST(latitude AS FLOAT64) > 39.9261  AND SAFE_CAST(latitude AS FLOAT64) < 39.9282 AND SAFE_CAST(longitude AS FLOAT64) < -105.1554 AND SAFE_CAST(longitude AS FLOAT64) > -105.1585 AND SAFE_CAST(geo_altitude AS FLOAT64) < 1833.372
ORDER BY TIMESTAMP_SECONDS(SAFE_CAST(time_position AS INT64)) DESC
LIMIT 300

**Comment by jzabel** [comment]
Since started, I see about 33 call signs who've failed to meet 500 ft above my house which is 150ft below the runway. As such, pilots like N523DL owned by Laurence Ioffredo (https://www.youtube.com/watch?v=G8RCTafhJd8) seemed to purposely fly low. With a 3% glide off the end of the runway, pilots should be 690' above my house; however, this guy on Saturday 10/21 7:19pm was only 5975 feet which is a mere 325ft of climb in 2 miles off the end of the runway. Plus, he had a vertical rate of -0.81 indicating he was actually descending over the neighborhood. Perhaps retaliation for the AG meeting?

**Comment by hoopyfrood1006** [comment]
Creating a ticket for the creation of a noiselogger-specific topographic map file that can either be queried or preferably saved for local processsing.

**Comment by jzabel** [comment]
Completed - in dashboard. Open a new issue to pull in geographical point altitude.
